# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=40)),
                ('data', models.DateTimeField()),
                ('temperatura', models.IntegerField()),
                ('umidade', models.IntegerField()),
            ],
        ),
    ]
